---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: English Content
- type: directory
  path: _carousel_highlights/en
  label: Carousel Highlights
  create: documents
  match: "*.md"
  templates:
  - carousel-highlights
- type: directory
  path: _posts
  label: News
  create: documents
  match: "*.md"
  templates:
  - post
- type: directory
  path: _upcoming_events
  label: Upcoming Events
  create: documents
  match: "*.md"
  templates:
  - upcoming_event
- type: document
  path: _data/collaborators.yml
  label: 'Collaborators '
- type: heading
  label: Spanish Content
- type: directory
  path: _carousel_highlights/es
  label: Páginas de Carrusel
  create: documents
  match: "*.md"
  templates:
  - pagina-de-carrusel
- type: directory
  path: _noticias
  label: Noticias
  create: documents
  match: "*.md"
  templates:
  - noticia
- type: directory
  path: _proximos_eventos
  label: Próximos Eventos
  create: documents
  match: "*.md"
  templates:
  - proximo-evento
- type: document
  path: _data/colaboradores.yml
  label: Colaboradores
- type: heading
  label: General
- type: document
  path: _data/information.yml
  label: Site Info
- type: document
  path: _data/board_of_directors.yml
  label: Board of Directors
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
instant_preview: true
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
